server:
  port: 9090

spring:
  datasource:
    url: jdbc:mariadb://database-tripian.cytjplhkopfw.ap-northeast-2.rds.amazonaws.com:3306/tripianDB
    username: tripian
    password: tripian1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
